### PR TITLE
Add empty prod.exs config file

### PR DESCRIPTION
**Pull request by legoscia**
config/config.exs tries to import the config file for the current Mix
environment. When including ex_aws_dynamo in an Erlang project using
rebar_mix, the Mix environment is always 'prod', so this fails because
there is no prod.exs file. Let's add an empty prod.exs file to work
around that.

### CODE REVIEW

**Comment by darrenklein** [comment]
Thanks very much for helping to maintain this project.

**Comment by legoscia** [comment]
Could you create a release on Hex with this change? Somehow rebar_mix isn't picking up dependencies from the git checkout.

**Comment by darrenklein** [comment]
@legoscia done - that's been published as version 3.0.2.

**Comment by legoscia** [comment]
Thank you!

**Pull request merged**
