### PR TITLE
Decode sets as MapSet

### PR DESCRIPTION
**Pull request by stocks29**
MapSet encodes to either a dynamo stringset (SS) or number set (NS). When decoding, they currently decode to a list. Wouldn't it be more natural if they decoded to a MapSet? That is what this PR does.

### CODE REVIEW

**Comment by hirocaster** [comment]
Sounds good, but Incompatible changes.

**Comment by hirocaster** [comment]
I think that this change should be added to the next major version.

**Comment by darrenklein** [comment]
@stocks29 Thanks very much for your interest - I've recently started to help maintain this repo, and am taking a look at the pending PRs while I'm learning more about the project.  Can you give me a little insight into your reasoning behind this PR?  Why would it be more natural to decode to MapSet rather than List?

**Comment by darrenklein** [comment]
@stocks29 Actually, I see what you're referring to (reading the issue you posted was very helpful) - mapsets encode to Dynamo NS/SS types, so NS SS types should decode to mapsets.  That makes sense to me.

As @hirocaster noted, this would be a breaking change, since you are effectively changing the data type that will ultimately be returned to the user from a list to a mapset - can you offer some thoughts on the best way to instruct users to adapt to this breaking change?  When it comes time to do the major version bump, I'd include some upgrade instructions.

**Comment by stocks29** [comment]
Perhaps we can include a config option in the short term allowing users to opt in to take advantage of this new functionality early. Then make it the default at the next major version.

Thoughts?

**Comment by darrenklein** [comment]
@stocks29 Yes, I think that sounds good - then we could just do a minor version upgrade this time around.  Would you like to go ahead and add that logic to your work?

**Comment by stocks29** [comment]
@darrenklein PR has been updated to enable mapset decoding by setting `decode_sets: true` in `:ex_aws`' `:dynamodb` configuration at compile time. I added `mix test.all` to run the tests with default configuration (`MIX_ENV=test mix test`) as well as with set decoding enabled (`MIX_ENV=test_options mix test`). This way we can easily rely on the tests to help maintain both variations. I didn't see any CI setup otherwise I would have updated that to use `mix test.all`.

Let me know if this works for you.

**Comment by darrenklein** [comment]
@stocks29 Great, thank you so much for your work on this. I'm moving very soon so I will be tied up for a few days, but will review your contribution later this week.

**Comment by stocks29** [comment]
Sounds good. Best of luck with your move.

**Comment by darrenklein** [comment]
@stocks29 @hirocaster I'm getting ready to cut the next major release, and so I've made some adjustments to the decoder so that the behavior that you corrected with the config option in this PR will now be the default behavior - this is currently on the `v3rc` branch - can I ask you to take a look, maybe even try it out and see if you think it looks good?

This version bump also changes the JSON codec used in `dev` and `test` environments from Poison to Jason - a few months ago, `ex_aws` changed their default codec to Jason, and so this is in keeping pace with that.  If your parent app doesn't include Jason, you'll need to add it to the deps, or provide configuration for `ex_aws` that specifies the codec that you want to use (I've added a directory called "upgrade_guides" that explains all of this).

Thanks!

**Comment by darrenklein** [comment]
This is now the default behavior as of version 3.0.0, 8fd0c4d4b12b89f8207220231fdbe68b4a0d75d0

**Pull request merged**
