### PR TITLE
Fix `decode_item/1,2` spec

### PR DESCRIPTION
**Pull request by danilagamma**
`decode_item/1,2` can work with `Items` and return a list of `map()`s.
@bernardd please review.

### CODE REVIEW

**Comment by darrenklein** [comment]
@danilagamma thanks for your help in maintaining and improving this project!

**Comment by danilagamma** [comment]
@darrenklein any chance this can get tagged for new release? 🙏

**Comment by darrenklein** [comment]
@danilagamma done, that's 4.2.1

**Comment by danilagamma** [comment]
Thank you :)

**Pull request merged**
